require 'temple'

require 'slim/indenter'
require 'slim/progress'
require 'slim/scanning_parser'
require 'slim/scanner'
require 'slim/code_finder'

require 'slim/syntaxes/nontag_processor'
require 'slim/syntaxes/tag_processor'

require 'slim/parser'
require 'slim/filter'
require 'slim/end_inserter'
require 'slim/embedded_engine'
require 'slim/interpolation'
require 'slim/control_structures'
require 'slim/splat_attributes'
require 'slim/code_attributes'
require 'slim/engine'
require 'slim/template'
require 'slim/version'
